In [4]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code
Enter your authorization code:
··········
Mounted at /gdrive

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [15]:
os.listdir('/gdrive/My Drive/MLC/bitcoin-historical-data')

['bitstampUSD_1-min_data_2012-01-01_to_2018-06-27.csv',
 'bitflyerJPY_1-min_data_2017-07-04_to_2018-06-27.csv',
 'coincheckJPY_1-min_data_2014-10-31_to_2018-06-27.csv',
 'coinbaseUSD_1-min_data_2014-12-01_to_2018-06-27.csv']

In [16]:
pd.read_csv("/gdrive/My Drive/MLC/bitcoin-historical-data/coinbaseUSD_1-min_data_2014-12-01_to_2018-06-27.csv")

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1417411980,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
1,1417412040,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
2,1417412100,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
3,1417412160,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
4,1417412220,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
5,1417412280,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
6,1417412340,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
7,1417412400,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
8,1417412460,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
9,1417412520,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
10,1417412580,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
11,1417412640,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
12,1417412700,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
13,1417412760,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
14,1417412820,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
15,1417412880,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
16,1417412940,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
17,1417413000,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
18,1417413060,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
19,1417413120,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
20,1417413180,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
21,1417413240,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
22,1417413300,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
23,1417413360,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
24,1417413420,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
25,1417413480,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
26,1417413540,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
27,1417413600,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
28,1417413660,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
29,1417413720,300.00,300.00,300.00,300.00,0.010000,3.000000e+00,300.000000
...,...,...,...,...,...,...,...,...
1819044,1530055860,6138.05,6138.05,6131.00,6131.00,3.912121,2.399707e+04,6134.030831
1819045,1530055920,6131.01,6131.01,6120.84,6120.84,38.624883,2.367755e+05,6130.128486
1819046,1530055980,6120.83,6120.83,6119.13,6119.13,26.353725,1.612907e+05,6120.222838
1819047,1530056040,6119.13,6119.14,6105.52,6105.52,18.117768,1.108240e+05,6116.866147
1819048,1530056100,6105.52,6107.02,6100.35,6100.35,22.443270,1.369749e+05,6103.161193
1819049,1530056160,6100.01,6104.19,6092.11,6103.48,12.532631,7.639967e+04,6096.059759
1819050,1530056220,6103.47,6119.13,6095.11,6109.01,18.790399,1.148144e+05,6110.269641
1819051,1530056280,6109.02,6109.02,6100.00,6100.01,7.631874,4.658682e+04,6104.244173
1819052,1530056340,6100.00,6100.01,6096.19,6096.19,7.210643,4.398471e+04,6099.970525
1819053,1530056400,6095.35,6111.67,6095.35,6111.67,4.117127,2.512208e+04,6101.846787
1819054,1530056460,6111.66,6111.67,6107.53,6109.99,3.666525,2.240357e+04,6110.300305
1819055,1530056520,6109.99,6110.00,6101.48,6103.70,3.929562,2.399803e+04,6107.050568
1819056,1530056580,6103.56,6103.57,6089.04,6097.05,32.778777,1.997259e+05,6093.147650
1819057,1530056640,6103.32,6103.58,6103.32,6103.58,2.420030,1.477083e+04,6103.571977
1819058,1530056700,6103.58,6103.58,6091.00,6099.46,4.066706,2.479840e+04,6097.908276
1819059,1530056760,6099.47,6099.47,6006.39,6049.54,328.442812,1.987433e+06,6051.078196
1819060,1530056820,6049.54,6068.25,6048.00,6068.24,96.390870,5.837419e+05,6055.987154
1819061,1530056880,6068.25,6079.99,6066.81,6066.81,14.085675,8.555354e+04,6073.797829
1819062,1530056940,6066.09,6066.10,6048.00,6048.01,16.698673,1.011007e+05,6054.412458
1819063,1530057000,6051.01,6065.99,6051.01,6059.99,8.968766,5.431224e+04,6055.709674
1819064,1530057060,6060.00,6065.99,6059.99,6065.99,7.226659,4.380306e+04,6061.315276
1819065,1530057120,6065.99,6079.06,6065.98,6078.06,29.526121,1.791363e+05,6067.046199
1819066,1530057180,6078.06,6078.06,6060.00,6065.98,17.584980,1.067265e+05,6069.185637
1819067,1530057240,6065.98,6070.15,6065.00,6065.00,1.244344,7.550332e+03,6067.721299
1819068,1530057300,6065.00,6070.16,6060.01,6064.02,2.516637,1.526347e+04,6065.027431
1819069,1530057360,6064.03,6080.00,6064.03,6080.00,10.561973,6.414883e+04,6073.564990
1819070,1530057420,6080.00,6080.00,6071.52,6077.99,0.682001,4.145298e+03,6078.136687
1819071,1530057480,6078.00,6081.00,6077.99,6081.00,5.710185,3.470863e+04,6078.372515
1819072,1530057540,6081.00,6085.70,6074.00,6074.00,20.892658,1.270504e+05,6081.105271
1819073,1530057600,6074.01,6074.01,6071.52,6071.53,33.898112,2.058961e+05,6073.969960

In [18]:
"/gdrive/My Drive/MLC/bitcoin-historical-data/coinbaseUSD_1-min_data_2014-12-01_to_2018-06-27.csv"

'/gdrive/My Drive/MLC/bitcoin-historical-data/coinbaseUSD_1-min_data_2014-12-01_to_2018-06-27.csv'

In [0]:
df = pd.read_csv("/gdrive/My Drive/MLC/bitcoin-historical-data/coinbaseUSD_1-min_data_2014-12-01_to_2018-06-27.csv")

In [21]:
df.head()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1417411980,300.0,300.0,300.0,300.0,0.01,3.0,300.0
1,1417412040,300.0,300.0,300.0,300.0,0.01,3.0,300.0
2,1417412100,300.0,300.0,300.0,300.0,0.01,3.0,300.0
3,1417412160,300.0,300.0,300.0,300.0,0.01,3.0,300.0
4,1417412220,300.0,300.0,300.0,300.0,0.01,3.0,300.0